return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "stylua",
      "shellcheck",
      "shfmt",
      "flake8",
      "ruff_lsp",
      "ruff",
      "pyright",
      "shfmt",
      "ansiblels",
      "ansible-lint",
      "bashls",
      "gitui",
      "jsonls",
      "lua_ls",
      "markdown-toc",
      "markdownlint-cli2",
      "marksman",
      "shellcheck",
      "stylua",
      "terraformls",
      "tflint",
      "ts_ls",
      "vtsls",
    },
  },
}
